#
# Super simple example of a Dockerfile
#
FROM ubuntu:18.04
MAINTAINER Andrew Odewahn "odewahn@oreilly.com"

RUN apt-get update
RUN apt-get install -y python python-pip wget

RUN pip install hello-world-py
